### ISSUE TITLE
HTML/Word output lacking new StanDoc attributes

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-rsd#18]
Such as:

* publish date
* revision date

**Comment by opoudjis** [comment]
The revision date currently is included conditionally in the title page, only if the document type is "Policy And Procedures" or "Proposal".

Slotted the published date as an alternative to the unpublished status. It's not clear to me what other new Standoc attributes you had in mind for adding?

**Comment by ronaldtse** [comment]
Thanks. I don't remember what the other ones are, but we can leave them for later. Thanks!
